# -*- coding: utf-8 -*-
"""engenharia-de-contexto-e-logica-fisica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xRNcY9Bg6eEN8PUa6N8HzEua7yMACrTa
"""

def analise_de_conforto_urbano(temp, umidade, iqa):

 # Use matemática complexa: comece com 10 e penalize os extremos

 nota = 10

 if temp > 30 or temp < 15:

  nota -= 2

 if iqa > 100:

  nota -= 3

 # Adicione sua própria lógica aqui

 return max(0, nota)

def main ():

 # Lista de Listas: [Local, Temp, Umidade, IQA]

 dados_locais = [

   ["Praça Arbonizada (P1, nome da praça em questão)", 28, 45, 35],

   ["Cruzamento Olavo Egidio", 31, 65, 60],

   ["Ponto de Ônibus da Monsenhor Meireles", 24, 55, 90]

 ]

 print("--- Análise de Microclima Local ---")

 for local in dados_locais:

  nome, temp, umid, iqa = local # Desempacotando a lista

  # Classificação com Match-Case

  match iqa:

   case iqa if iqa <= 50:

    classificação = "Boa"

   case iqa if iqa <= 100:

    classificação = "Moderado"

   case _:

    classificação = "Ruim/Alerta"



  nota_final = analise_de_conforto_urbano(temp,umid, iqa)

  print(f"Local: {nome} | IQA: {classificação} | Nota conforto: {nota_final}/10")

if __name__ == "__main__":

  main()











def simulador_evacuacao():

  locais = ["Quarto", "Corredor", "Sala", "Cozinha", "Saída"]

  estados = ["Livre", "Porta Trancada", "Livre", "Chave no Chão", "Final"]

  inventario = []

  posicao = 0 # Começa no quarto (Índece 0)

  energia = 10

  print("Iniciando Simulação de Evacuação...")



  while posicao < len(locais) and energia > 0: # Corrected while loop syntax and added energy check

    local_atual = locais[posicao] # Define local_atual

    estado_atual = estados[posicao]



    print(f"Você está no(a) {local_atual} (Energia: {energia})")



    # Lógica de decisão

    if estado_atual == "Chave no Chão": # Added colon and corrected case

      print("Encontrou uma chave! Coletando...")

      inventario.append("chave")

      posicao += 1

      energia -= 1 # Assume collecting takes energy

    elif estado_atual == "Porta Trancada": # Added colon

      if "chave" in inventario:

        print("Usou a chave para abrir a porta.")

        posicao += 1

        energia -= 1

      else:

        print("Porta trancada e sem chave. Retrocedendo!")

        posicao -= 1 # Retrocedendo na lista

        if posicao < 0:

          posicao = 0 # Prevent going below start

        energia -= 1 # Retroceding also consumes energy

    else: # This 'else' covers 'Livre' or 'Final' if not already handled

      print("Caminho livre. Avançando...")

      posicao += 1

      energia -= 1



    # Check for game end conditions after movement

    if posicao >= len(locais): # Reached the exit or went past it

      print("Você chegou à saída com segurança!")

      break # Exit loop

    elif energia <= 0: # Ran out of energy

      print("Você ficou sem energia e não conseguiu escapar.")

      break



  # Final message if the loop completes without a break (shouldn't happen with breaks above)

  # This part is mostly for robustness, though the breaks handle most termination messages.

  if energia > 0 and posicao < len(locais):

    print("A simulação terminou, mas você não chegou à saída (provavelmente preso).")



simulador_evacuacao()











# Com o desenvolvimento da parte dois dessa atividade, eu sinto que desenvolvi uma melhor analise dos ambientes que entro e saio diariamente, pensamentos em as milhares de formas que se podem desenrolar as coisas, múltiplas possibilidades de saídas e entradas, analise dos locais que as coisas se encontram devido a ações anteriores de outras pessoas.